---

- name: Set variables
  set_fact: 
    aws_login: false

- name: Enable ECR login
  set_fact:
    aws_login: true
  when: 
    - '"dkr.ecr" in image or "public.ecr" in image'
    - customer_key is defined
    - skip_molecule_task is not defined

- name: Login to AWS for ECR
  include_role:
    name: docker/ecr
  when: aws_login

- name: Docker login
  community.docker.docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
  when: 
    - docker_username is defined
    - docker_password is defined
    - not aws_login

- name: Reading path to Python repository with Docker package
  command: "{{ ansible_python_interpreter }} -c \"import docker as _; print(_.__file__.replace('/docker/__init__.py', ''))\""
  register: python_packages_path_output
  changed_when: python_packages_path_output.rc != 0

- name: Set path to Docker Python package
  set_fact:
    python_packages_path: "{{ python_packages_path_output.stdout_lines | first }}"

- name: Set docker full image name
  set_fact:
    full_image_name: "{{ image }}:{{ tag }}"
