#!/usr/bin/env bash

export DOCKERFILE_PATH=${DOCKERFILE_PATH:-Dockerfile}

echo "Executing build command"
echo "docker build --build-arg ml_base_aurora_branch=${SOURCE_BRANCH} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} ."

docker build --build-arg ml_base_aurora_branch="${SOURCE_BRANCH}" -f "${DOCKERFILE_PATH}" -t "${IMAGE_NAME}" .
